# Task 1 — Topological spatial relation qualification

Reproduction of the experiment done by Ji et al (2025) using Jev by TypesafeAI instead of GPT-4. The same data and evaluation methods are used. Prompts are adapted to the Jev model and different prompting strategies (instructions and criteria) are tested.

Input: Two WKT geometries
Output: Topological predicate


Ji, Y., Gao, S., Nie, Y., Majić, I., & Janowicz, K. (2025). Foundation models for geospatial reasoning: Assessing the capabilities of large language models in understanding geometries and topological spatial relations. International Journal of Geographical Information Science, 39(9), 1866–1903. https://doi.org/10.1080/13658816.2025.2511227

## Imports and functions

In [1]:
import pandas as pd
from tqdm import tqdm
from tqdm.asyncio import tqdm 
from datetime import datetime
import os
import json
import numpy as np
from dotenv import load_dotenv
x = load_dotenv()

from typesafe_sdk import Choice, TypeSafeClient, AsyncTypeSafeClient

In [16]:
def format_duration(td):
    total_seconds = int(td.total_seconds())
    hours = total_seconds // 3600
    minutes = (total_seconds % 3600) // 60
    seconds = total_seconds % 60
    return f"{hours:02}:{minutes:02}:{seconds:02} (h:m:s)"

def create_metadata(instructions, criteria, task, criteria_dict, instructions_dict, model):
    meta = {}
    meta['Title'] = f'Task{task}_ins-{instructions}_cri-{criteria}'
    meta['Date'] = datetime.now().strftime('%Y/%m/%d %H:%M')
    meta['Task'] = task

    meta['instructions_id'] = instructions
    meta['instructions'] = instructions_dict[instructions]
    meta['criteria_id'] = criteria
    meta['criteria'] = criteria_dict[criteria]
    meta['model'] = model

    path = f"results/{meta['Title']}.json"
    i = 0

    while os.path.exists(path):
        i += 1
        path = f"results/{meta['Title']}"
        path = f"{path}_{i}.json"

    with open(f'{path}', 'x', encoding='utf-8') as f:
        json.dump(meta, f, indent=4, ensure_ascii=False)
        print(f'Saved {path}')

    return path

async def async_jev(instructions, criteria, state, model):
    starttime = datetime.now()
    response = await client.system_one(
        model=model,
        state=state,
        questions={
            "Task": Choice(
                instructions=instructions,
                criteria=criteria,
            )
        },
    )
    endtime = datetime.now()
    time = str(endtime - starttime)

    return response, time

# Main function. Includes the entire workflow after metadata creation including data saving.
async def async_jev_main(instructions, criteria, criteria_dict, instructions_dict, model, path):
    results = []
    tasks = []
    
    for _, row in relations_test.iterrows():
        if instructions == 'ji-fewshot':
            examples = get_examples(row)
            state = f"Geometry A: {row.geometry}, Geometry B: {row.geometry_subject}. Examples: {examples}"
        elif instructions == 'ji-fewshot-CoT':
            examples = get_examples_cot(row)
            state = f"Geometry A: {row.geometry}, Geometry B: {row.geometry_subject}. Examples: {examples}"
        else:
            state = f"Geometry A: {row.geometry}, Geometry B: {row.geometry_subject}"
        
        task = async_jev(instructions_dict[instructions], criteria_dict[criteria], state, model)
        tasks.append(task)

    results_raw = await tqdm.gather(*tasks, desc="Prompting")

    for i, (response, time) in enumerate(results_raw):
        row = relations_test.iloc[i] # Match the result to the original row
        result = {
            'GeomA': row.geometry,
            'GeomB': row.geometry_subject,
            'predicate': row.predicate,
            'choice': response.answers['Task'].choice,
            'probabilities': str(response.answers['Task'].probabilities),
            'confidence': response.answers['Task'].confidence,
            'correct': int(response.answers['Task'].choice == row.predicate),
            'input_tokens': response.usage.input_tokens,
            'output_tokens': response.usage.output_tokens,
            'time': time
        }
        results.append(result)

    results_df = pd.DataFrame(results)
    save_data(path, results_df)

def cost_estimation(instructions, criteria, criteria_dict, instructions_dict):
    inst = instructions_dict[instructions]
    crit = criteria_dict[criteria]
    total = 0
    for i, row in relations_test.iterrows():
        relations_example = relations[relations['idx']>=200].reset_index(drop=True)
        if instructions == 'ji-fewshot':
            examples = get_examples(row)
            state = f"Geometry A: {row.geometry}, Geometry B: {row.geometry_subject}. Examples: {examples}"
        elif instructions == 'ji-fewshot-CoT':
            relations_example = relations_example[relations_example['idx']==200]
            examples = get_examples_cot(row)
            state = f"Geometry A: {row.geometry}, Geometry B: {row.geometry_subject}. Examples: {examples}"
        else:
            state = f"Geometry A: {row.geometry}, Geometry B: {row.geometry_subject}"

        prompt = f"{inst} {crit} {state}"
        total += len(prompt) // 3
    return total

def print_summary(metadata):
    with open(metadata, 'r', encoding='utf-8') as js:
        meta = json.load(js)
    if os.path.exists(metadata.replace('.json', '.csv')):
        results_df = pd.read_csv(metadata.replace('.json', '.csv'))
    else:
        print('No results available yet.')
        return

    high_conf = results_df[results_df['confidence'].astype(float)>=0.8]
    mid_conf = results_df[(results_df['confidence'].astype(float)<0.8) & (results_df['confidence'].astype(float)>=0.5)]
    low_conf = results_df[results_df['confidence'].astype(float)<0.5]

    summary = f"""
        Summary of results for {meta['Title']}:
        Date: {meta['Date']}
        Tokens used: {int(meta['Input Tokens']) + int(meta['Output Tokens'])}
        Time taken (synchronous): {meta['Duration']}

        Total: {results_df.shape[0]} results, {round(results_df['correct'].mean()*100, 2)}% correct.
        Confidence above 80%: {high_conf.shape[0]} results, {round(high_conf['correct'].mean()*100, 2)}% correct.
        Confidence between 50 and 80%: {mid_conf.shape[0]} results, {round(mid_conf['correct'].mean()*100, 2)}% correct.
        Confidence below 50%: {low_conf.shape[0]} results, {round(low_conf['correct'].mean()*100, 2)}% correct.\n
    """
    return summary

def save_data(metadata, results_df):
    with open(metadata, 'r', encoding='utf-8') as js:
        meta = json.load(js)
    results_df.to_csv(metadata.replace('.json', '.csv'), index=False)

    meta['Input Tokens'] = int(results_df['input_tokens'].astype(int).sum())
    meta['Output Tokens'] = int(results_df['output_tokens'].astype(int).sum())
    meta['Duration'] = format_duration(pd.to_timedelta(results_df['time']).sum())
    meta['Accuracy'] = f'{round(results_df['correct'].mean()*100, 2)}%'
    meta['Results'] = results_df.shape[0]

    with open(f'{metadata}', 'w', encoding='utf-8') as f:
        json.dump(meta, f, indent=4, ensure_ascii=False)
        print(f'Saved {metadata}')

    print(print_summary(metadata))

    return metadata

# Gets examples from relations_example for few-shot prompting. Input is a row from relations_test. Copied from Ji, with minor changes to fit my code
def get_examples(row):
    
    np.random.seed()
    geom_type_subject = row['geom_type_subject']
    geom_type = row['geom_type']
    # create the example set
    df = relations_example[(relations_example['geom_type_subject']==geom_type_subject) &
                            (relations_example['geom_type']==geom_type)]
    examples_df = df[['geometry_subject', 'geometry', 'predicate']].sample(5)
    examples = f""
    for _, row in examples_df.iterrows():
        examples += f"Geometry A: {row['geometry']}; Geometry B: {row['geometry_subject']}; Answer: {row['predicate']}\n"
    return examples

# Gets examples from relations_example for few-shot prompting in CoT config. Copied from Ji, no changes. Used in get_example_cot
def get_cot_example(row):
    relate = list(row['relate'])
    WKT_A = row['geometry_subject']
    WKT_B = row['geometry']
    Type_A = row['geom_type_subject']
    Type_B = row['geom_type']

    example = f"""
First, let's determine the geometry types of A and B.
Geometry A is a {Type_A}.
Geometry B is a {Type_B}.

"""
    predicate = None
    # within = False
    # contains = False

    idx = 1
    IA_IB = 'No' if row['predicate'] in ['disjoint', 'touches'] else 'Yes' #relate[0]=='F' else 'Yes'
    example += f"{idx}. Does the Interior of A intersect the Interior of B? \n{IA_IB}\n"
    idx+=1



    if IA_IB == 'No':
        BA_BB = 'No' if row['predicate']=='disjoint' else 'Yes' #relate[4]=='F' else 'Yes'
        example += f"{idx}. Does A intersect B? \n{BA_BB}\n"
        idx+=1

        if BA_BB=='No':
            predicate = 'disjoint'
        else:
            predicate = 'touches'

        example += f"\nSo {Type_A} A {predicate} {Type_B} B.\n"


    else:
        IA_IB = 'Yes' if (row['predicate'] in ['within', 'equals']) else 'No'
        example += f"{idx}. Does the intersection of A and B equal to  A? \n{IA_IB}\n"
        idx+=1

        if IA_IB=='Yes':
            contains = "No" if row['predicate']=='Within' else "Yes"
            example += f"{idx}. Does the intersection of  A and  B equal to  B? \n{contains}\n"
            idx += 1
            if contains=="No":
                predicate = 'within'
                example += f"So {Type_A} A {predicate} {Type_B} B.\n"

            else:
                predicate = 'equals'
                example += f"So {Type_A} A is {predicate} {Type_B} B.\n"


        if (IA_IB=='No'):
            IA_IB = 'Yes' if (row['predicate'] in ['contains']) else 'No'
            example += f"{idx}. Does the intersection of  A and  B equal to  B? \n{IA_IB}\n"
            idx+=1

            if IA_IB=='Yes':
                predicate = 'contains'
                example += f"So {Type_A} A {predicate} {Type_B} B.\n"
            else:
                Dim = 'No' if (row['predicate']=='crosses') else 'Yes'

                # example += f"""{idx}. Let Dim(A) be the dimension of the Interior of A,
                # Dim(B) be the dimension of the Interior of B, Dim(AB) be the dimension of
                # the Interior of the intersection of A and B. Does Dim(AB)=max(Dim(A), Dim(B))-1 hold? \n{Dim}\n"""
                example += f"""{idx}. Are A an B of the same dimension and
                  their intersection set results in a geometry different from both but of the same dimension?\n{Dim}\n"""
                idx+=1

                if Dim=='No':
                    predicate = 'crosses'
                else:
                    predicate = 'overlaps'
                example += f"So {Type_A} A {predicate} {Type_B} B.\n"


    example += f"ANSWER: ({Type_A}, {predicate}, {Type_B})"

    # print('---------')
    # print(row['predicate'], predicate)
    # print(example)

    return example

# Function get_examples adapted for CoT. Copied from Ji with the same changes as above.
def get_examples_cot(row):
    geom_type_subject = row['geom_type_subject']
    geom_type = row['geom_type']
    # create the example set
    df = relations_example[(relations_example['geom_type_subject']==geom_type_subject) &
                            (relations_example['geom_type']==geom_type)]

    df['example'] = df.apply(lambda row: get_cot_example(row), axis=1)

    examples_df = df[['geometry_subject', 'geometry', 'example']].sample(5)

    examples = f""
    for _, row in examples_df.iterrows():
        examples += f"Geometry A: {row['geometry']}; Geometry B: {row['geometry_subject']}; Reasoning: {row['example']}\n"

    return examples

## Data and Prompts

In [3]:
# Same data as in Ji

relations = pd.read_csv('relations.csv')
relations_test = relations[relations['idx']<40].reset_index(drop=True)
relations_example = relations[relations['idx']>=200].reset_index(drop=True)
# relations_example = relations_example[relations_example['idx']==200]

### Original prompts by Ji
These are the prompts Ji used in their paper taken from the provided code (Code/task1/task1-GPT-4.ipynb).  
Accompanying the prompt-originals are their performance with GPT-4 and information if they have been translated for use in my reproduction. My translations are very close to the original, fixing minor errors and removing information irrelevant for a typesafe model.

Notes:  
CoT is contradictive to system-1-intelligence. I still tested it.  
The 'dimension requirement' was included in all later prompts by Ji. I did so too.  
With few-shot prompts the examples are added to the state during execution.  
CoT few-shot and normal few-shot have differently structured examples.

#### Zero Shot without dimension requirement
Accuracy: 0.632  
Translated to: ji-0shot

SYSTEM_PROMPT = """You will be given the WKT format of geometries given the subject A and reference object B.
Classify their spatial relations into one of the following predicates: contains, within, touches, equals, crosses, disjoint, overlaps.
The predicates are defined by DE-9IM and Open Geospatial Consortium. If A equals to B, there is no need to return 'within' or 'contains'.

- Return in the format (Geometry type A, PREDICATE, geometry type B), and nothing else. Geometry types are Point, LineString, Polygon.
- MAKE SURE the PREDICATE in your output is one of the seven predicates stated."""

USER_PROMPT = """
Geometry A: {WKT_A}
Geometry B: {WKT_B}
"""


#### Zero-Shot with dimension requirement
Accuracy: 0.635
Translated to: ji-0shot-dim

SYSTEM_PROMPT = """You will be given the WKT format of geometries given the subject A and reference object B.
Classify their spatial relations into one of the following predicates: contains, within, touches, equals, crosses, disjoint, overlaps.
The predicates are defined by DE-9IM and Open Geospatial Consortium. If A equals to B, there is no need to return 'within' or 'contains'.

- Return in the format (Geometry type A, PREDICATE, geometry type B), and nothing else. Geometry types are Point, LineString, Polygon.
- MAKE SURE the PREDICATE in your output is one of the seven predicates stated.
- MAKE SURE the PREDICATE satisfies the the dimension requirements defined by DE-9IM and OGC given Geometry Type A and Geometry Type B.
"""

USER_PROMPT = """
Geometry A: {WKT_A}
Geometry B: {WKT_B}
"""

#### Few-Shot
Accuracy: 0.666 (winner)
Translated to: ji-fewshot

prefix = """
You will be given the WKT format of geometries given the subject A and reference object B.
Classify their spatial relations into one of the following predicates: contains, within, touches, equals, crosses, disjoint, overlaps.
The predicates are defined by DE-9IM and Open Geospatial Consortium. If A equals to B, there is no need to return 'within' or 'contains'.

- Return in the format (Geometry type A, PREDICATE, geometry type B), and nothing else. Geometry types are Point, LineString, Polygon.
- MAKE SURE the PREDICATE in your output is one of the seven predicates stated.
- MAKE SURE the PREDICATE satisfies the the dimension requirements defined by DE-9IM and OGC given Geometry Type A and Geometry Type B.
- TRY YOUR BEST to understand how the spatial relations in the examples are determined.


[EXAMPLES]
"""

suffix = """
[END EXAMPLES]

Geometry A: {WKT_A}
Geometry B: {WKT_B}
Desired output:
"""


#### Zero-Shot CoT
Accuracy: 0.610
Translated to: ji-0shot-CoT

SYSTEM_PROMPT = """You will be given the WKT format of geometries given the subject A and reference object B.
Classify their spatial relations into one of the following predicates: contains, within, touches, equals, crosses, disjoint, overlaps.
The predicates are defined by DE-9IM and Open Geospatial Consortium. If A equals to B, there is no need to return 'within' or 'contains'.

- MAKE SURE the rationale is complete, professional, consistent, coherent, and accurate to derive the answer for the classification task.
- MAKE SURE the output ends with the 'ANSWER: (Geometry Type A, PREDICATE, Geometry Type B)', where the [Predicate] is one of the seven predicates stated,
and the Geometry types are Point, LineString, Polygon.
- MAKE SURE the PREDICATE satisfies the the dimension requirements defined by DE-9IM and OGC given Geometry Type A and Geometry Type B.
"""

USER_PROMPT = """
Geometry A: {WKT_A}
Geometry B: {WKT_B}
"""

AI_PROMPT = """
Let's think step by step.
"""


#### Few-Shot CoT
Accuracy: 0.627
Translated to: ji-fewshot-CoT

prefix = """You will be given the WKT format of geometries given the subject A and reference object B.
Classify their spatial relations into one of the following predicates: contains, within, touches, equals, crosses, disjoint, overlaps.
The predicates are defined by DE-9IM and Open Geospatial Consortium. If A equals to B, there is no need to return 'within' or 'contains'.

- MAKE SURE the rationale is complete, professional, consistent, coherent, and accurate to derive the answer for the classification task.
- MAKE SURE the output ends with the 'ANSWER: (Geometry Type A, PREDICATE, Geometry Type B)', where the PREDICATE is one of the seven predicates stated,
and the Geometry Types are Point, LineString, Polygon.
- MAKE SURE the PREDICATE satisfies the the dimension requirements defined by DE-9IM and OGC given Geometry Type A and Geometry Type B.
- MAKE SURE the same decision process as shown in the examples is used to reason about the answer.
- DO NOT ask repeated questions.

[EXAMPLES]
"""

"""You will be given the WKT format of geometries given the subject A and reference object B.
Classify their spatial relations into one of the following predicates: contains, within, touches, equals, crosses, disjoint, overlaps.
The predicates are defined by DE-9IM and Open Geospatial Consortium. If A equals to B, there is no need to return 'within' or 'contains'.

MAKE SURE the rationale is complete.
MAKE SURE the answer ends with the 'ANSWER: (geometry type A, predicate, geometry type B)', where the Geometry types are Point, LineString, Polygon.
and the predicate is one of the six predicates stated. """

suffix = """
[END EXAMPLES]

Geometry A: {WKT_A}
Geometry B: {WKT_B}
Desired output:
"""

In [4]:
instructions_dict = {
    'basic': "What topological predicate best describes the relationship between Place A and Place B? The predicates follow the definition of DE-9IM.",
    'ji-0shot': "You will be given the WKT format of geometries given the subject A and reference object B. Classify their spatial relations into one of the predicates defined by DE-9IM and the Open Geospatial Consortium. If A equals to B, there is no need to return 'within' or 'contains'.",
    'ji-0shot-dim': "You will be given the WKT format of geometries given the subject A and reference object B. Classify their spatial relations into one of the predicates defined by DE-9IM and the Open Geospatial Consortium. If A equals to B, there is no need to return 'within' or 'contains'. MAKE SURE the PREDICATE satisfies the dimension requirements defined by DE-9IM and OGC given Geometry Type A and Geometry Type B.",
    'ji-fewshot': "You will be given the WKT format of geometries given the subject A and reference object B and some solved examples to learn from. Classify their spatial relations into one of the predicates defined by DE-9IM and the Open Geospatial Consortium. If A equals to B, there is no need to return 'within' or 'contains'. MAKE SURE the PREDICATE satisfies the dimension requirements defined by DE-9IM and OGC given Geometry Type A and Geometry Type B.",
    'ji-0shot-CoT': "You will be given the WKT format of geometries given the subject A and reference object B. Classify their spatial relations into one of the predicates defined by DE-9IM and the Open Geospatial Consortium. If A equals to B, there is no need to return 'within' or 'contains'. Let's think step by step.",
    'ji-fewshot-CoT': "You will be given the WKT format of geometries given the subject A and reference object B and some solved examples to learn from. Classify their spatial relations into one of the predicates defined by DE-9IM and the Open Geospatial Consortium. If A equals to B, there is no need to return 'within' or 'contains'. MAKE SURE the PREDICATE satisfies the dimension requirements defined by DE-9IM and OGC given Geometry Type A and Geometry Type B. Let's think step by step.",
}

In [6]:
criteria_dict = {
    'basic': {
        "contains": "",
        "within": "",
        "touches": "",
        "crosses": "",
        "disjoint": "",
        "overlaps": "",
        "equals": "",
    }
}

In [98]:
# Tests

# Data tests
# print(relations_test.shape[0])
# relations_test[['objectid', 'geom_type', 'geom_type_subject', 'predicate']].groupby(['geom_type_subject', 'predicate', 'geom_type']).count()

# Example of Few-Shot examples
# print(get_examples(relations_test.iloc[0]))

# Example of Few-Shot CoT examples
print(get_examples_cot(relations_test.iloc[0]))

Geometry A: LINESTRING (-89.3576 43.0311, -89.3576 43.0312); Geometry B: LINESTRING (-89.3576 43.0311, -89.3576 43.03117, -89.3576 43.0312); Reasoning:
First, let's determine the geometry types of A and B.
Geometry A is a LineString.
Geometry B is a LineString.

1. Does the Interior of A intersect the Interior of B?
Yes
2. Does the intersection of A and B equal to  A?
Yes
3. Does the intersection of  A and  B equal to  B?
Yes
So LineString A is equals LineString B.
ANSWER: (LineString, equals, LineString)
Geometry A: LINESTRING (-89.2982 43.095, -89.2982 43.0946); Geometry B: LINESTRING (-89.2965 43.095, -89.2966 43.0935, -89.2982 43.0936, -89.2982 43.095, -89.2965 43.095); Reasoning:
First, let's determine the geometry types of A and B.
Geometry A is a LineString.
Geometry B is a LineString.

1. Does the Interior of A intersect the Interior of B?
Yes
2. Does the intersection of A and B equal to  A?
No
3. Does the intersection of  A and  B equal to  B?
Yes
So LineString A contains LineString B.
ANSWER: (LineString, contains, LineString)
Geometry A: LINESTRING (-89.4904 43.0065, -89.49033 43.0065, -89.4903 43.0065); Geometry B: LINESTRING (-89.4904 43.0065, -89.4903 43.0065); Reasoning:
First, let's determine the geometry types of A and B.
Geometry A is a LineString.
Geometry B is a LineString.

1. Does the Interior of A intersect the Interior of B?
Yes
2. Does the intersection of A and B equal to  A?
Yes
3. Does the intersection of  A and  B equal to  B?
Yes
So LineString A is equals LineString B.
ANSWER: (LineString, equals, LineString)
Geometry A: LINESTRING (-89.4554 43.0111, -89.4554 43.01131, -89.4554 43.0114); Geometry B: LINESTRING (-89.4554 43.0114, -89.4564 43.0115); Reasoning:
First, let's determine the geometry types of A and B.
Geometry A is a LineString.
Geometry B is a LineString.

1. Does the Interior of A intersect the Interior of B?
No
2. Does A intersect B?
Yes

So LineString A touches LineString B.
ANSWER: (LineString, touches, LineString)
Geometry A: LINESTRING (-89.3932 43.1338, -89.3953 43.1338); Geometry B: LINESTRING (-89.3928 43.1338, -89.3932 43.1338); Reasoning:
First, let's determine the geometry types of A and B.
Geometry A is a LineString.
Geometry B is a LineString.

1. Does the Interior of A intersect the Interior of B?
No
2. Does A intersect B?
Yes

So LineString A touches LineString B.
ANSWER: (LineString, touches, LineString)

## Execution

In [ ]:
# Dry test and cost estimation
# Last estimation undershot by 50 cent (4 characters = 1 token). Changed to 3 character per token and it only undershot by 10 cents.
model = 'jev-1.13.0'

estimate = 0
price = 0.042 / 1000000
repeats = 10

for ins in instructions_dict.keys():
    for crit in criteria_dict.keys():
        this_run = cost_estimation(ins, crit, criteria_dict, instructions_dict)
        estimate += this_run
        print(f"Instructions: {ins}, Criteria: {crit}, Tokens: {this_run:,}, Cost: {this_run*price:.2f}$")
            

print(f"""
    Total tokens: {estimate*repeats:,}
    Total cost: {estimate*price*repeats:.2f}$
    """)

Instructions: basic, Criteria: basic, Tokens: 227,157, Cost: 0.01$
Instructions: ji-0shot, Criteria: basic, Tokens: 291,557, Cost: 0.01$
Instructions: ji-0shot-dim, Criteria: basic, Tokens: 352,222, Cost: 0.01$
Instructions: ji-fewshot, Criteria: basic, Tokens: 968,091, Cost: 0.04$
Instructions: ji-0shot-CoT, Criteria: basic, Tokens: 303,695, Cost: 0.01$
Instructions: ji-fewshot-CoT, Criteria: basic, Tokens: 1,744,386, Cost: 0.07$

    Total tokens: 38,871,080
    Total cost: 1.63$

In [8]:
# ASYNCHROUNOUS EXECUTION (running this cell costs money)
# Pre run credits: $4.61

for i in range(repeats):
    print(f'Starting run {i}/{repeats}.')
    for ins in instructions_dict.keys():
        for crit in criteria_dict.keys():
            path = create_metadata(ins, crit, '1', criteria_dict, instructions_dict, model)
            client = AsyncTypeSafeClient()
            await async_jev_main(ins, crit, criteria_dict, instructions_dict, model, path)

Starting run 0/10.
Saved results/Task1_ins-basic_cri-basic.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 294.76it/s]

Saved results/Task1_ins-basic_cri-basic.json

        Summary of results for Task1_ins-basic_cri-basic:
        Date: 2026/10/21 21:07
        Tokens used: 868299
        Time taken (synchronous): 01:07:01 (h:m:s)

        Total: 1400 results, 35.79% correct.
        Confidence above 80%: 350 results, 92.0% correct.
        Confidence between 50 and 80%: 380 results, 20.53% correct.
        Confidence below 50%: 670 results, 15.07% correct.


Saved results/Task1_ins-ji-0shot_cri-basic.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 298.23it/s]

Saved results/Task1_ins-ji-0shot_cri-basic.json

        Summary of results for Task1_ins-ji-0shot_cri-basic:
        Date: 2026/10/21 21:07
        Tokens used: 921363
        Time taken (synchronous): 01:07:31 (h:m:s)

        Total: 1400 results, 43.86% correct.
        Confidence above 80%: 322 results, 87.27% correct.
        Confidence between 50 and 80%: 499 results, 27.25% correct.
        Confidence below 50%: 579 results, 34.02% correct.


Saved results/Task1_ins-ji-0shot-dim_cri-basic.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 291.51it/s]

Saved results/Task1_ins-ji-0shot-dim_cri-basic.json

        Summary of results for Task1_ins-ji-0shot-dim_cri-basic:
        Date: 2026/10/21 21:07
        Tokens used: 963315
        Time taken (synchronous): 01:07:39 (h:m:s)

        Total: 1400 results, 43.79% correct.
        Confidence above 80%: 361 results, 73.41% correct.
        Confidence between 50 and 80%: 516 results, 29.84% correct.
        Confidence below 50%: 523 results, 37.09% correct.


Saved results/Task1_ins-ji-fewshot_cri-basic.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 288.93it/s]

Saved results/Task1_ins-ji-fewshot_cri-basic.json

        Summary of results for Task1_ins-ji-fewshot_cri-basic:
        Date: 2026/10/21 21:08
        Tokens used: 2358686
        Time taken (synchronous): 01:08:34 (h:m:s)

        Total: 1400 results, 38.21% correct.
        Confidence above 80%: 57 results, 84.21% correct.
        Confidence between 50 and 80%: 394 results, 50.51% correct.
        Confidence below 50%: 949 results, 30.35% correct.


Saved results/Task1_ins-ji-0shot-CoT_cri-basic.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 295.47it/s]

Saved results/Task1_ins-ji-0shot-CoT_cri-basic.json

        Summary of results for Task1_ins-ji-0shot-CoT_cri-basic:
        Date: 2026/10/21 21:08
        Tokens used: 931177
        Time taken (synchronous): 01:08:05 (h:m:s)

        Total: 1400 results, 44.57% correct.
        Confidence above 80%: 315 results, 91.43% correct.
        Confidence between 50 and 80%: 528 results, 26.7% correct.
        Confidence below 50%: 557 results, 35.01% correct.


Saved results/Task1_ins-ji-fewshot-CoT_cri-basic.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 285.94it/s]

Saved results/Task1_ins-ji-fewshot-CoT_cri-basic.json

        Summary of results for Task1_ins-ji-fewshot-CoT_cri-basic:
        Date: 2026/10/21 21:08
        Tokens used: 3018373
        Time taken (synchronous): 01:08:45 (h:m:s)

        Total: 1400 results, 33.5% correct.
        Confidence above 80%: 33 results, 63.64% correct.
        Confidence between 50 and 80%: 424 results, 43.16% correct.
        Confidence below 50%: 943 results, 28.1% correct.


Starting run 1/10.
Saved results/Task1_ins-basic_cri-basic_1.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 281.90it/s]

Saved results/Task1_ins-basic_cri-basic_1.json

        Summary of results for Task1_ins-basic_cri-basic:
        Date: 2026/10/21 21:08
        Tokens used: 868298
        Time taken (synchronous): 01:08:42 (h:m:s)

        Total: 1400 results, 36.29% correct.
        Confidence above 80%: 355 results, 90.99% correct.
        Confidence between 50 and 80%: 381 results, 20.73% correct.
        Confidence below 50%: 664 results, 15.96% correct.


Saved results/Task1_ins-ji-0shot_cri-basic_1.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 290.12it/s]

Saved results/Task1_ins-ji-0shot_cri-basic_1.json

        Summary of results for Task1_ins-ji-0shot_cri-basic:
        Date: 2026/10/21 21:08
        Tokens used: 921357
        Time taken (synchronous): 01:09:29 (h:m:s)

        Total: 1400 results, 43.79% correct.
        Confidence above 80%: 324 results, 87.96% correct.
        Confidence between 50 and 80%: 508 results, 27.17% correct.
        Confidence below 50%: 568 results, 33.45% correct.


Saved results/Task1_ins-ji-0shot-dim_cri-basic_1.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 290.69it/s]

Saved results/Task1_ins-ji-0shot-dim_cri-basic_1.json

        Summary of results for Task1_ins-ji-0shot-dim_cri-basic:
        Date: 2026/10/21 21:08
        Tokens used: 963325
        Time taken (synchronous): 01:07:31 (h:m:s)

        Total: 1400 results, 44.0% correct.
        Confidence above 80%: 361 results, 72.3% correct.
        Confidence between 50 and 80%: 530 results, 29.43% correct.
        Confidence below 50%: 509 results, 39.1% correct.


Saved results/Task1_ins-ji-fewshot_cri-basic_1.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 288.58it/s]

Saved results/Task1_ins-ji-fewshot_cri-basic_1.json

        Summary of results for Task1_ins-ji-fewshot_cri-basic:
        Date: 2026/10/21 21:08
        Tokens used: 2357803
        Time taken (synchronous): 01:08:10 (h:m:s)

        Total: 1400 results, 37.29% correct.
        Confidence above 80%: 41 results, 80.49% correct.
        Confidence between 50 and 80%: 379 results, 49.08% correct.
        Confidence below 50%: 980 results, 30.92% correct.


Saved results/Task1_ins-ji-0shot-CoT_cri-basic_1.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 288.08it/s]

Saved results/Task1_ins-ji-0shot-CoT_cri-basic_1.json

        Summary of results for Task1_ins-ji-0shot-CoT_cri-basic:
        Date: 2026/10/21 21:08
        Tokens used: 931168
        Time taken (synchronous): 01:07:55 (h:m:s)

        Total: 1400 results, 44.86% correct.
        Confidence above 80%: 329 results, 90.58% correct.
        Confidence between 50 and 80%: 520 results, 27.12% correct.
        Confidence below 50%: 551 results, 34.3% correct.


Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_1.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 290.07it/s]

Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_1.json

        Summary of results for Task1_ins-ji-fewshot-CoT_cri-basic:
        Date: 2026/10/21 21:08
        Tokens used: 3036722
        Time taken (synchronous): 01:09:26 (h:m:s)

        Total: 1400 results, 32.86% correct.
        Confidence above 80%: 49 results, 69.39% correct.
        Confidence between 50 and 80%: 398 results, 39.45% correct.
        Confidence below 50%: 953 results, 28.23% correct.


Starting run 2/10.
Saved results/Task1_ins-basic_cri-basic_2.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 296.25it/s]

Saved results/Task1_ins-basic_cri-basic_2.json

        Summary of results for Task1_ins-basic_cri-basic:
        Date: 2026/10/21 21:08
        Tokens used: 868306
        Time taken (synchronous): 01:07:12 (h:m:s)

        Total: 1400 results, 36.07% correct.
        Confidence above 80%: 347 results, 91.64% correct.
        Confidence between 50 and 80%: 381 results, 21.78% correct.
        Confidence below 50%: 672 results, 15.48% correct.


Saved results/Task1_ins-ji-0shot_cri-basic_2.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 289.84it/s]

Saved results/Task1_ins-ji-0shot_cri-basic_2.json

        Summary of results for Task1_ins-ji-0shot_cri-basic:
        Date: 2026/10/21 21:09
        Tokens used: 921371
        Time taken (synchronous): 01:09:43 (h:m:s)

        Total: 1400 results, 43.36% correct.
        Confidence above 80%: 320 results, 87.5% correct.
        Confidence between 50 and 80%: 512 results, 26.56% correct.
        Confidence below 50%: 568 results, 33.63% correct.


Saved results/Task1_ins-ji-0shot-dim_cri-basic_2.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 286.68it/s]

Saved results/Task1_ins-ji-0shot-dim_cri-basic_2.json

        Summary of results for Task1_ins-ji-0shot-dim_cri-basic:
        Date: 2026/10/21 21:09
        Tokens used: 963319
        Time taken (synchronous): 01:07:45 (h:m:s)

        Total: 1400 results, 44.14% correct.
        Confidence above 80%: 358 results, 73.18% correct.
        Confidence between 50 and 80%: 507 results, 29.59% correct.
        Confidence below 50%: 535 results, 38.5% correct.


Saved results/Task1_ins-ji-fewshot_cri-basic_2.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 288.40it/s]

Saved results/Task1_ins-ji-fewshot_cri-basic_2.json

        Summary of results for Task1_ins-ji-fewshot_cri-basic:
        Date: 2026/10/21 21:09
        Tokens used: 2361402
        Time taken (synchronous): 01:08:39 (h:m:s)

        Total: 1400 results, 37.71% correct.
        Confidence above 80%: 52 results, 84.62% correct.
        Confidence between 50 and 80%: 386 results, 48.96% correct.
        Confidence below 50%: 962 results, 30.67% correct.


Saved results/Task1_ins-ji-0shot-CoT_cri-basic_2.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 293.29it/s]

Saved results/Task1_ins-ji-0shot-CoT_cri-basic_2.json

        Summary of results for Task1_ins-ji-0shot-CoT_cri-basic:
        Date: 2026/10/21 21:09
        Tokens used: 931168
        Time taken (synchronous): 01:08:25 (h:m:s)

        Total: 1400 results, 44.71% correct.
        Confidence above 80%: 319 results, 92.16% correct.
        Confidence between 50 and 80%: 525 results, 27.05% correct.
        Confidence below 50%: 556 results, 34.17% correct.


Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_2.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 290.86it/s]

Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_2.json

        Summary of results for Task1_ins-ji-fewshot-CoT_cri-basic:
        Date: 2026/10/21 21:09
        Tokens used: 3003153
        Time taken (synchronous): 01:08:10 (h:m:s)

        Total: 1400 results, 30.93% correct.
        Confidence above 80%: 39 results, 61.54% correct.
        Confidence between 50 and 80%: 408 results, 37.99% correct.
        Confidence below 50%: 953 results, 26.65% correct.


Starting run 3/10.
Saved results/Task1_ins-basic_cri-basic_3.json

Prompting: 100%|██████████| 1400/1400 [00:05<00:00, 269.18it/s]

Saved results/Task1_ins-basic_cri-basic_3.json

        Summary of results for Task1_ins-basic_cri-basic:
        Date: 2026/10/21 21:09
        Tokens used: 868294
        Time taken (synchronous): 01:07:52 (h:m:s)

        Total: 1400 results, 35.57% correct.
        Confidence above 80%: 346 results, 92.2% correct.
        Confidence between 50 and 80%: 382 results, 20.68% correct.
        Confidence below 50%: 672 results, 14.88% correct.


Saved results/Task1_ins-ji-0shot_cri-basic_3.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 300.19it/s]

Saved results/Task1_ins-ji-0shot_cri-basic_3.json

        Summary of results for Task1_ins-ji-0shot_cri-basic:
        Date: 2026/10/21 21:09
        Tokens used: 921366
        Time taken (synchronous): 01:06:39 (h:m:s)

        Total: 1400 results, 44.29% correct.
        Confidence above 80%: 314 results, 88.85% correct.
        Confidence between 50 and 80%: 519 results, 27.94% correct.
        Confidence below 50%: 567 results, 34.57% correct.


Saved results/Task1_ins-ji-0shot-dim_cri-basic_3.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 287.55it/s]

Saved results/Task1_ins-ji-0shot-dim_cri-basic_3.json

        Summary of results for Task1_ins-ji-0shot-dim_cri-basic:
        Date: 2026/10/21 21:09
        Tokens used: 963312
        Time taken (synchronous): 01:08:20 (h:m:s)

        Total: 1400 results, 43.57% correct.
        Confidence above 80%: 362 results, 72.65% correct.
        Confidence between 50 and 80%: 512 results, 29.88% correct.
        Confidence below 50%: 526 results, 36.88% correct.


Saved results/Task1_ins-ji-fewshot_cri-basic_3.json

Prompting: 100%|██████████| 1400/1400 [00:05<00:00, 270.98it/s]

Saved results/Task1_ins-ji-fewshot_cri-basic_3.json

        Summary of results for Task1_ins-ji-fewshot_cri-basic:
        Date: 2026/10/21 21:09
        Tokens used: 2343622
        Time taken (synchronous): 01:07:55 (h:m:s)

        Total: 1400 results, 35.86% correct.
        Confidence above 80%: 49 results, 69.39% correct.
        Confidence between 50 and 80%: 393 results, 46.31% correct.
        Confidence below 50%: 958 results, 29.85% correct.


Saved results/Task1_ins-ji-0shot-CoT_cri-basic_3.json

Prompting: 100%|██████████| 1400/1400 [00:05<00:00, 268.46it/s]

Saved results/Task1_ins-ji-0shot-CoT_cri-basic_3.json

        Summary of results for Task1_ins-ji-0shot-CoT_cri-basic:
        Date: 2026/10/21 21:09
        Tokens used: 931164
        Time taken (synchronous): 01:07:13 (h:m:s)

        Total: 1400 results, 44.21% correct.
        Confidence above 80%: 326 results, 91.1% correct.
        Confidence between 50 and 80%: 514 results, 25.29% correct.
        Confidence below 50%: 560 results, 34.29% correct.


Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_3.json

Prompting: 100%|██████████| 1400/1400 [00:05<00:00, 279.82it/s]

Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_3.json

        Summary of results for Task1_ins-ji-fewshot-CoT_cri-basic:
        Date: 2026/10/21 21:10
        Tokens used: 3020373
        Time taken (synchronous): 01:08:11 (h:m:s)

        Total: 1400 results, 31.64% correct.
        Confidence above 80%: 46 results, 71.74% correct.
        Confidence between 50 and 80%: 403 results, 41.44% correct.
        Confidence below 50%: 951 results, 25.55% correct.


Starting run 4/10.
Saved results/Task1_ins-basic_cri-basic_4.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 289.87it/s]

Saved results/Task1_ins-basic_cri-basic_4.json

        Summary of results for Task1_ins-basic_cri-basic:
        Date: 2026/10/21 21:10
        Tokens used: 868307
        Time taken (synchronous): 01:09:23 (h:m:s)

        Total: 1400 results, 35.64% correct.
        Confidence above 80%: 355 results, 90.99% correct.
        Confidence between 50 and 80%: 394 results, 20.56% correct.
        Confidence below 50%: 651 results, 14.59% correct.


Saved results/Task1_ins-ji-0shot_cri-basic_4.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 289.68it/s]

Saved results/Task1_ins-ji-0shot_cri-basic_4.json

        Summary of results for Task1_ins-ji-0shot_cri-basic:
        Date: 2026/10/21 21:10
        Tokens used: 921356
        Time taken (synchronous): 01:08:45 (h:m:s)

        Total: 1400 results, 43.86% correct.
        Confidence above 80%: 316 results, 87.97% correct.
        Confidence between 50 and 80%: 520 results, 27.5% correct.
        Confidence below 50%: 564 results, 34.22% correct.


Saved results/Task1_ins-ji-0shot-dim_cri-basic_4.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 293.54it/s]

Saved results/Task1_ins-ji-0shot-dim_cri-basic_4.json

        Summary of results for Task1_ins-ji-0shot-dim_cri-basic:
        Date: 2026/10/21 21:10
        Tokens used: 963305
        Time taken (synchronous): 01:08:25 (h:m:s)

        Total: 1400 results, 43.79% correct.
        Confidence above 80%: 354 results, 74.29% correct.
        Confidence between 50 and 80%: 520 results, 27.5% correct.
        Confidence below 50%: 526 results, 39.35% correct.


Saved results/Task1_ins-ji-fewshot_cri-basic_4.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 281.98it/s]

Saved results/Task1_ins-ji-fewshot_cri-basic_4.json

        Summary of results for Task1_ins-ji-fewshot_cri-basic:
        Date: 2026/10/21 21:10
        Tokens used: 2345154
        Time taken (synchronous): 01:08:45 (h:m:s)

        Total: 1400 results, 37.5% correct.
        Confidence above 80%: 43 results, 76.74% correct.
        Confidence between 50 and 80%: 360 results, 53.89% correct.
        Confidence below 50%: 997 results, 29.89% correct.


Saved results/Task1_ins-ji-0shot-CoT_cri-basic_4.json

Prompting: 100%|██████████| 1400/1400 [00:05<00:00, 277.12it/s]

Saved results/Task1_ins-ji-0shot-CoT_cri-basic_4.json

        Summary of results for Task1_ins-ji-0shot-CoT_cri-basic:
        Date: 2026/10/21 21:10
        Tokens used: 931179
        Time taken (synchronous): 01:10:06 (h:m:s)

        Total: 1400 results, 44.36% correct.
        Confidence above 80%: 320 results, 91.25% correct.
        Confidence between 50 and 80%: 521 results, 26.68% correct.
        Confidence below 50%: 559 results, 33.99% correct.


Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_4.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 291.18it/s]

Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_4.json

        Summary of results for Task1_ins-ji-fewshot-CoT_cri-basic:
        Date: 2026/10/21 21:10
        Tokens used: 3016257
        Time taken (synchronous): 01:07:55 (h:m:s)

        Total: 1400 results, 30.43% correct.
        Confidence above 80%: 41 results, 51.22% correct.
        Confidence between 50 and 80%: 408 results, 36.76% correct.
        Confidence below 50%: 951 results, 26.81% correct.


Starting run 5/10.
Saved results/Task1_ins-basic_cri-basic_5.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 292.41it/s]

Saved results/Task1_ins-basic_cri-basic_5.json

        Summary of results for Task1_ins-basic_cri-basic:
        Date: 2026/10/21 21:10
        Tokens used: 868300
        Time taken (synchronous): 01:06:50 (h:m:s)

        Total: 1400 results, 35.57% correct.
        Confidence above 80%: 351 results, 90.6% correct.
        Confidence between 50 and 80%: 388 results, 22.42% correct.
        Confidence below 50%: 661 results, 14.07% correct.


Saved results/Task1_ins-ji-0shot_cri-basic_5.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 299.99it/s]

Saved results/Task1_ins-ji-0shot_cri-basic_5.json

        Summary of results for Task1_ins-ji-0shot_cri-basic:
        Date: 2026/10/21 21:10
        Tokens used: 921379
        Time taken (synchronous): 01:07:42 (h:m:s)

        Total: 1400 results, 44.36% correct.
        Confidence above 80%: 308 results, 87.66% correct.
        Confidence between 50 and 80%: 521 results, 27.45% correct.
        Confidence below 50%: 571 results, 36.43% correct.


Saved results/Task1_ins-ji-0shot-dim_cri-basic_5.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 294.77it/s]

Saved results/Task1_ins-ji-0shot-dim_cri-basic_5.json

        Summary of results for Task1_ins-ji-0shot-dim_cri-basic:
        Date: 2026/10/21 21:10
        Tokens used: 963309
        Time taken (synchronous): 01:07:35 (h:m:s)

        Total: 1400 results, 44.0% correct.
        Confidence above 80%: 364 results, 71.7% correct.
        Confidence between 50 and 80%: 513 results, 29.82% correct.
        Confidence below 50%: 523 results, 38.62% correct.


Saved results/Task1_ins-ji-fewshot_cri-basic_5.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 286.60it/s]

Saved results/Task1_ins-ji-fewshot_cri-basic_5.json

        Summary of results for Task1_ins-ji-fewshot_cri-basic:
        Date: 2026/10/21 21:10
        Tokens used: 2358889
        Time taken (synchronous): 01:08:19 (h:m:s)

        Total: 1400 results, 35.36% correct.
        Confidence above 80%: 47 results, 91.49% correct.
        Confidence between 50 and 80%: 404 results, 47.03% correct.
        Confidence below 50%: 949 results, 27.61% correct.


Saved results/Task1_ins-ji-0shot-CoT_cri-basic_5.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 280.16it/s]

Saved results/Task1_ins-ji-0shot-CoT_cri-basic_5.json

        Summary of results for Task1_ins-ji-0shot-CoT_cri-basic:
        Date: 2026/10/21 21:11
        Tokens used: 931188
        Time taken (synchronous): 01:09:16 (h:m:s)

        Total: 1400 results, 44.29% correct.
        Confidence above 80%: 317 results, 92.11% correct.
        Confidence between 50 and 80%: 520 results, 27.31% correct.
        Confidence below 50%: 563 results, 33.04% correct.


Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_5.json

Prompting: 100%|██████████| 1400/1400 [00:05<00:00, 278.26it/s]

Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_5.json

        Summary of results for Task1_ins-ji-fewshot-CoT_cri-basic:
        Date: 2026/10/21 21:11
        Tokens used: 3035329
        Time taken (synchronous): 01:09:04 (h:m:s)

        Total: 1400 results, 31.64% correct.
        Confidence above 80%: 44 results, 79.55% correct.
        Confidence between 50 and 80%: 415 results, 38.55% correct.
        Confidence below 50%: 941 results, 26.35% correct.


Starting run 6/10.
Saved results/Task1_ins-basic_cri-basic_6.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 291.54it/s]

Saved results/Task1_ins-basic_cri-basic_6.json

        Summary of results for Task1_ins-basic_cri-basic:
        Date: 2026/10/21 21:11
        Tokens used: 868292
        Time taken (synchronous): 01:07:39 (h:m:s)

        Total: 1400 results, 35.64% correct.
        Confidence above 80%: 357 results, 90.48% correct.
        Confidence between 50 and 80%: 388 results, 20.36% correct.
        Confidence below 50%: 655 results, 14.81% correct.


Saved results/Task1_ins-ji-0shot_cri-basic_6.json

Prompting: 100%|██████████| 1400/1400 [00:05<00:00, 279.38it/s]

Saved results/Task1_ins-ji-0shot_cri-basic_6.json

        Summary of results for Task1_ins-ji-0shot_cri-basic:
        Date: 2026/10/21 21:11
        Tokens used: 921366
        Time taken (synchronous): 01:09:14 (h:m:s)

        Total: 1400 results, 43.5% correct.
        Confidence above 80%: 314 results, 88.85% correct.
        Confidence between 50 and 80%: 508 results, 26.97% correct.
        Confidence below 50%: 578 results, 33.39% correct.


Saved results/Task1_ins-ji-0shot-dim_cri-basic_6.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 291.30it/s]

Saved results/Task1_ins-ji-0shot-dim_cri-basic_6.json

        Summary of results for Task1_ins-ji-0shot-dim_cri-basic:
        Date: 2026/10/21 21:11
        Tokens used: 963310
        Time taken (synchronous): 01:08:18 (h:m:s)

        Total: 1400 results, 43.79% correct.
        Confidence above 80%: 354 results, 73.16% correct.
        Confidence between 50 and 80%: 517 results, 28.63% correct.
        Confidence below 50%: 529 results, 38.94% correct.


Saved results/Task1_ins-ji-fewshot_cri-basic_6.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 291.64it/s]

Saved results/Task1_ins-ji-fewshot_cri-basic_6.json

        Summary of results for Task1_ins-ji-fewshot_cri-basic:
        Date: 2026/10/21 21:11
        Tokens used: 2353891
        Time taken (synchronous): 01:08:34 (h:m:s)

        Total: 1400 results, 35.21% correct.
        Confidence above 80%: 47 results, 78.72% correct.
        Confidence between 50 and 80%: 411 results, 44.77% correct.
        Confidence below 50%: 942 results, 28.87% correct.


Saved results/Task1_ins-ji-0shot-CoT_cri-basic_6.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 297.34it/s]

Saved results/Task1_ins-ji-0shot-CoT_cri-basic_6.json

        Summary of results for Task1_ins-ji-0shot-CoT_cri-basic:
        Date: 2026/10/21 21:11
        Tokens used: 931167
        Time taken (synchronous): 01:07:21 (h:m:s)

        Total: 1400 results, 44.43% correct.
        Confidence above 80%: 324 results, 90.43% correct.
        Confidence between 50 and 80%: 527 results, 27.32% correct.
        Confidence below 50%: 549 results, 33.7% correct.


Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_6.json

Prompting: 100%|██████████| 1400/1400 [00:05<00:00, 268.08it/s]

Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_6.json

        Summary of results for Task1_ins-ji-fewshot-CoT_cri-basic:
        Date: 2026/10/21 21:11
        Tokens used: 3023163
        Time taken (synchronous): 01:08:26 (h:m:s)

        Total: 1400 results, 31.36% correct.
        Confidence above 80%: 40 results, 65.0% correct.
        Confidence between 50 and 80%: 399 results, 40.1% correct.
        Confidence below 50%: 961 results, 26.33% correct.


Starting run 7/10.
Saved results/Task1_ins-basic_cri-basic_7.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 301.93it/s]

Saved results/Task1_ins-basic_cri-basic_7.json

        Summary of results for Task1_ins-basic_cri-basic:
        Date: 2026/10/21 21:11
        Tokens used: 868291
        Time taken (synchronous): 01:06:11 (h:m:s)

        Total: 1400 results, 35.64% correct.
        Confidence above 80%: 351 results, 91.45% correct.
        Confidence between 50 and 80%: 373 results, 21.18% correct.
        Confidence below 50%: 676 results, 14.64% correct.


Saved results/Task1_ins-ji-0shot_cri-basic_7.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 296.82it/s]

Saved results/Task1_ins-ji-0shot_cri-basic_7.json

        Summary of results for Task1_ins-ji-0shot_cri-basic:
        Date: 2026/10/21 21:12
        Tokens used: 921374
        Time taken (synchronous): 01:08:09 (h:m:s)

        Total: 1400 results, 43.57% correct.
        Confidence above 80%: 316 results, 88.29% correct.
        Confidence between 50 and 80%: 508 results, 26.38% correct.
        Confidence below 50%: 576 results, 34.2% correct.


Saved results/Task1_ins-ji-0shot-dim_cri-basic_7.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 297.52it/s]

Saved results/Task1_ins-ji-0shot-dim_cri-basic_7.json

        Summary of results for Task1_ins-ji-0shot-dim_cri-basic:
        Date: 2026/10/21 21:12
        Tokens used: 963306
        Time taken (synchronous): 01:06:16 (h:m:s)

        Total: 1400 results, 43.43% correct.
        Confidence above 80%: 366 results, 71.86% correct.
        Confidence between 50 and 80%: 521 results, 30.33% correct.
        Confidence below 50%: 513 results, 36.45% correct.


Saved results/Task1_ins-ji-fewshot_cri-basic_7.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 287.71it/s]

Saved results/Task1_ins-ji-fewshot_cri-basic_7.json

        Summary of results for Task1_ins-ji-fewshot_cri-basic:
        Date: 2026/10/21 21:12
        Tokens used: 2372512
        Time taken (synchronous): 01:08:43 (h:m:s)

        Total: 1400 results, 37.86% correct.
        Confidence above 80%: 51 results, 80.39% correct.
        Confidence between 50 and 80%: 390 results, 49.49% correct.
        Confidence below 50%: 959 results, 30.87% correct.


Saved results/Task1_ins-ji-0shot-CoT_cri-basic_7.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 293.53it/s]

Saved results/Task1_ins-ji-0shot-CoT_cri-basic_7.json

        Summary of results for Task1_ins-ji-0shot-CoT_cri-basic:
        Date: 2026/10/21 21:12
        Tokens used: 931166
        Time taken (synchronous): 01:08:46 (h:m:s)

        Total: 1400 results, 44.21% correct.
        Confidence above 80%: 329 results, 91.19% correct.
        Confidence between 50 and 80%: 508 results, 27.36% correct.
        Confidence below 50%: 563 results, 31.97% correct.


Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_7.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 290.52it/s]

Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_7.json

        Summary of results for Task1_ins-ji-fewshot-CoT_cri-basic:
        Date: 2026/10/21 21:12
        Tokens used: 3033702
        Time taken (synchronous): 01:08:55 (h:m:s)

        Total: 1400 results, 32.43% correct.
        Confidence above 80%: 37 results, 72.97% correct.
        Confidence between 50 and 80%: 405 results, 41.48% correct.
        Confidence below 50%: 958 results, 27.04% correct.


Starting run 8/10.
Saved results/Task1_ins-basic_cri-basic_8.json

Prompting: 100%|██████████| 1400/1400 [00:05<00:00, 269.88it/s]

Saved results/Task1_ins-basic_cri-basic_8.json

        Summary of results for Task1_ins-basic_cri-basic:
        Date: 2026/10/21 21:12
        Tokens used: 868308
        Time taken (synchronous): 01:07:59 (h:m:s)

        Total: 1400 results, 35.43% correct.
        Confidence above 80%: 361 results, 90.86% correct.
        Confidence between 50 and 80%: 383 results, 19.06% correct.
        Confidence below 50%: 656 results, 14.48% correct.


Saved results/Task1_ins-ji-0shot_cri-basic_8.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 280.41it/s]

Saved results/Task1_ins-ji-0shot_cri-basic_8.json

        Summary of results for Task1_ins-ji-0shot_cri-basic:
        Date: 2026/10/21 21:12
        Tokens used: 921366
        Time taken (synchronous): 01:08:28 (h:m:s)

        Total: 1400 results, 43.57% correct.
        Confidence above 80%: 329 results, 88.15% correct.
        Confidence between 50 and 80%: 490 results, 25.71% correct.
        Confidence below 50%: 581 results, 33.39% correct.


Saved results/Task1_ins-ji-0shot-dim_cri-basic_8.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 284.82it/s]

Saved results/Task1_ins-ji-0shot-dim_cri-basic_8.json

        Summary of results for Task1_ins-ji-0shot-dim_cri-basic:
        Date: 2026/10/21 21:12
        Tokens used: 963302
        Time taken (synchronous): 01:08:48 (h:m:s)

        Total: 1400 results, 43.79% correct.
        Confidence above 80%: 365 results, 73.15% correct.
        Confidence between 50 and 80%: 513 results, 29.43% correct.
        Confidence below 50%: 522 results, 37.36% correct.


Saved results/Task1_ins-ji-fewshot_cri-basic_8.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 282.58it/s]

Saved results/Task1_ins-ji-fewshot_cri-basic_8.json

        Summary of results for Task1_ins-ji-fewshot_cri-basic:
        Date: 2026/10/21 21:12
        Tokens used: 2347747
        Time taken (synchronous): 01:08:28 (h:m:s)

        Total: 1400 results, 37.0% correct.
        Confidence above 80%: 40 results, 85.0% correct.
        Confidence between 50 and 80%: 394 results, 50.0% correct.
        Confidence below 50%: 966 results, 29.71% correct.


Saved results/Task1_ins-ji-0shot-CoT_cri-basic_8.json

Prompting: 100%|██████████| 1400/1400 [00:05<00:00, 272.42it/s]

Saved results/Task1_ins-ji-0shot-CoT_cri-basic_8.json

        Summary of results for Task1_ins-ji-0shot-CoT_cri-basic:
        Date: 2026/10/21 21:12
        Tokens used: 931174
        Time taken (synchronous): 01:07:18 (h:m:s)

        Total: 1400 results, 44.93% correct.
        Confidence above 80%: 319 results, 91.54% correct.
        Confidence between 50 and 80%: 516 results, 27.13% correct.
        Confidence below 50%: 565 results, 34.87% correct.


Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_8.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 292.42it/s]

Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_8.json

        Summary of results for Task1_ins-ji-fewshot-CoT_cri-basic:
        Date: 2026/10/21 21:12
        Tokens used: 3029600
        Time taken (synchronous): 01:07:37 (h:m:s)

        Total: 1400 results, 30.57% correct.
        Confidence above 80%: 34 results, 61.76% correct.
        Confidence between 50 and 80%: 413 results, 41.16% correct.
        Confidence below 50%: 953 results, 24.87% correct.


Starting run 9/10.
Saved results/Task1_ins-basic_cri-basic_9.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 293.53it/s]

Saved results/Task1_ins-basic_cri-basic_9.json

        Summary of results for Task1_ins-basic_cri-basic:
        Date: 2026/10/21 21:13
        Tokens used: 868308
        Time taken (synchronous): 01:06:43 (h:m:s)

        Total: 1400 results, 36.0% correct.
        Confidence above 80%: 354 results, 91.24% correct.
        Confidence between 50 and 80%: 386 results, 20.21% correct.
        Confidence below 50%: 660 results, 15.61% correct.


Saved results/Task1_ins-ji-0shot_cri-basic_9.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 296.82it/s]

Saved results/Task1_ins-ji-0shot_cri-basic_9.json

        Summary of results for Task1_ins-ji-0shot_cri-basic:
        Date: 2026/10/21 21:13
        Tokens used: 921357
        Time taken (synchronous): 01:07:47 (h:m:s)

        Total: 1400 results, 42.79% correct.
        Confidence above 80%: 316 results, 87.97% correct.
        Confidence between 50 and 80%: 509 results, 27.9% correct.
        Confidence below 50%: 575 results, 31.13% correct.


Saved results/Task1_ins-ji-0shot-dim_cri-basic_9.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 297.46it/s]

Saved results/Task1_ins-ji-0shot-dim_cri-basic_9.json

        Summary of results for Task1_ins-ji-0shot-dim_cri-basic:
        Date: 2026/10/21 21:13
        Tokens used: 963293
        Time taken (synchronous): 01:07:53 (h:m:s)

        Total: 1400 results, 43.21% correct.
        Confidence above 80%: 360 results, 72.78% correct.
        Confidence between 50 and 80%: 524 results, 29.96% correct.
        Confidence below 50%: 516 results, 36.05% correct.


Saved results/Task1_ins-ji-fewshot_cri-basic_9.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 290.65it/s]

Saved results/Task1_ins-ji-fewshot_cri-basic_9.json

        Summary of results for Task1_ins-ji-fewshot_cri-basic:
        Date: 2026/10/21 21:13
        Tokens used: 2355162
        Time taken (synchronous): 01:07:20 (h:m:s)

        Total: 1400 results, 36.29% correct.
        Confidence above 80%: 44 results, 70.45% correct.
        Confidence between 50 and 80%: 409 results, 48.41% correct.
        Confidence below 50%: 947 results, 29.46% correct.


Saved results/Task1_ins-ji-0shot-CoT_cri-basic_9.json

Prompting: 100%|██████████| 1400/1400 [00:04<00:00, 289.60it/s]

Saved results/Task1_ins-ji-0shot-CoT_cri-basic_9.json

        Summary of results for Task1_ins-ji-0shot-CoT_cri-basic:
        Date: 2026/10/21 21:13
        Tokens used: 931176
        Time taken (synchronous): 01:08:56 (h:m:s)

        Total: 1400 results, 44.57% correct.
        Confidence above 80%: 317 results, 92.11% correct.
        Confidence between 50 and 80%: 523 results, 27.72% correct.
        Confidence below 50%: 560 results, 33.39% correct.


Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_9.json

Prompting: 100%|██████████| 1400/1400 [00:05<00:00, 263.99it/s]

Saved results/Task1_ins-ji-fewshot-CoT_cri-basic_9.json

        Summary of results for Task1_ins-ji-fewshot-CoT_cri-basic:
        Date: 2026/10/21 21:13
        Tokens used: 3014970
        Time taken (synchronous): 01:09:32 (h:m:s)

        Total: 1400 results, 32.43% correct.
        Confidence above 80%: 44 results, 72.73% correct.
        Confidence between 50 and 80%: 431 results, 39.91% correct.
        Confidence below 50%: 925 results, 27.03% correct.

## Result Evaluation

I am disregarding geometry type in the experiment in the evaluation. The paper did so also, but it might be interesting (not sure).

In [45]:
# Combine all results to one dataframe

results_list = os.listdir('results')
all_results = []

for result in results_list:
    if result.endswith('.csv'):
        continue
    result = result.rstrip('.json')

    with open(f'results/{result}.json', 'r', encoding='utf-8') as js:
        meta = json.load(js)

    
    results_df = pd.read_csv(f'results/{result}.csv')

    high_conf = results_df[results_df['confidence'].astype(float)>=0.8]
    mid_conf = results_df[(results_df['confidence'].astype(float)<0.8) & (results_df['confidence'].astype(float)>=0.5)]
    low_conf = results_df[results_df['confidence'].astype(float)<0.5]

    result_dict = {
        'Title': meta['Title'],
        'Date': meta['Date'],
        'Instructions': meta['instructions_id'],
        'Criteria': meta['criteria_id'],
        'Input tokens': meta['Input Tokens'],
        'Results': results_df.shape[0],
        'Total %': round(results_df['correct'].mean()*100, 2),
        'High Conf': high_conf.shape[0],
        'High Conf %': round(high_conf['correct'].mean()*100, 2),
        'Mid Conf': mid_conf.shape[0],
        'Mid Conf %': round(mid_conf['correct'].mean()*100, 2),
        'Low Conf': low_conf.shape[0],
        'Low Conf %': round(low_conf['correct'].mean()*100, 2),
    }
    predicates = ["contains","within","touches","crosses","disjoint","overlaps","equals"]
    for pred in predicates:
        df = results_df[results_df['choice'] == pred]
        correct = round(df['correct'].mean()*100, 2)
        result_dict[f'{pred}%'] = float(correct)

    all_results.append(result_dict)

all_results_df = pd.DataFrame(all_results)
all_results_df.sort_values('Instructions')

,Title,Date,Instructions,Criteria,Input tokens,Results,Total %,High Conf,High Conf %,Mid Conf,Mid Conf %,Low Conf,Low Conf %,contains%,within%,touches%,crosses%,disjoint%,overlaps%,equals%
29,Task1_ins-basic_cri-basic,2026/10/21 21:08,basic,basic,764950,1400,36.29,355,90.99,381,20.73,664,15.96,1.72,0.64,48.34,33.33,83.16,51.79,91.25
2,Task1_ins-basic_cri-basic,2026/10/21 21:09,basic,basic,764950,1400,35.57,346,92.20,382,20.68,672,14.88,1.23,0.32,48.03,50.00,82.90,41.07,91.25
27,Task1_ins-basic_cri-basic,2026/10/21 21:07,basic,basic,764950,1400,35.79,350,92.00,380,20.53,670,15.07,1.74,0.31,45.96,33.33,83.99,45.28,93.59
50,Task1_ins-basic_cri-basic,2026/10/21 21:11,basic,basic,764950,1400,35.64,351,91.45,373,21.18,676,14.64,1.73,0.31,47.65,33.33,83.33,45.61,91.03
49,Task1_ins-basic_cri-basic,2026/10/21 21:11,basic,basic,764950,1400,35.64,357,90.48,388,20.36,655,14.81,1.47,0.32,48.34,37.50,83.55,46.55,89.61
47,Task1_ins-basic_cri-basic,2026/10/21 21:13,basic,basic,764950,1400,36.00,354,91.24,386,20.21,660,15.61,1.98,0.32,48.37,33.33,82.95,46.67,90.79
44,Task1_ins-basic_cri-basic,2026/10/21 21:10,basic,basic,764950,1400,35.64,355,90.99,394,20.56,651,14.59,1.00,0.31,49.04,36.36,83.38,41.18,91.03
42,Task1_ins-basic_cri-basic,2026/10/21 21:08,basic,basic,764950,1400,36.07,347,91.64,381,21.78,672,15.48,1.95,0.33,47.97,42.86,83.46,46.55,90.79
33,Task1_ins-basic_cri-basic,2026/10/21 21:10,basic,basic,764950,1400,35.57,351,90.60,388,22.42,661,14.07,1.00,0.31,48.37,44.44,83.07,44.83,92.11
31,Task1_ins-basic_cri-basic,2026/10/21 21:12,basic,basic,764950,1400,35.43,361,90.86,383,19.06,656,14.48,0.99,0.32,47.71,35.71,82.86,46.30,90.79
24,Task1_ins-ji-0shot_cri-basic,2026/10/21 21:12,ji-0shot,basic,818150,1400,43.57,329,88.15,490,25.71,581,33.39,0.00,19.78,68.57,22.22,86.31,34.72,88.89
58,Task1_ins-ji-0shot_cri-basic,2026/10/21 21:10,ji-0shot,basic,818150,1400,44.36,308,87.66,521,27.45,571,36.43,0.00,20.17,67.96,50.00,85.83,35.06,90.91
43,Task1_ins-ji-0shot_cri-basic,2026/10/21 21:09,ji-0shot,basic,818150,1400,44.29,314,88.85,519,27.94,567,34.57,0.00,20.22,70.19,57.14,86.67,36.49,90.48
54,Task1_ins-ji-0shot_cri-basic,2026/10/21 21:11,ji-0shot,basic,818150,1400,43.50,314,88.85,508,26.97,578,33.39,0.00,19.65,67.62,37.50,86.03,33.78,90.62
55,Task1_ins-ji-0shot_cri-basic,2026/10/21 21:12,ji-0shot,basic,818150,1400,43.57,316,88.29,508,26.38,576,34.20,0.00,19.62,69.90,40.00,85.32,34.21,89.06
22,Task1_ins-ji-0shot_cri-basic,2026/10/21 21:07,ji-0shot,basic,818150,1400,43.86,322,87.27,499,27.25,579,34.02,0.00,20.57,66.33,33.33,85.40,35.62,89.39
17,Task1_ins-ji-0shot_cri-basic,2026/10/21 21:09,ji-0shot,basic,818150,1400,43.36,320,87.50,512,26.56,568,33.63,0.00,19.59,66.35,33.33,85.67,33.33,87.50
59,Task1_ins-ji-0shot_cri-basic,2026/10/21 21:13,ji-0shot,basic,818150,1400,42.79,316,87.97,509,27.90,575,31.13,0.00,19.07,67.96,12.50,85.99,33.80,89.06
3,Task1_ins-ji-0shot_cri-basic,2026/10/21 21:10,ji-0shot,basic,818150,1400,43.86,316,87.97,520,27.50,564,34.22,0.00,20.08,69.00,28.57,85.87,32.86,91.04
13,Task1_ins-ji-0shot_cri-basic,2026/10/21 21:08,ji-0shot,basic,818150,1400,43.79,324,87.96,508,27.17,568,33.45,0.00,20.16,68.04,33.33,85.64,36.36,90.77
38,Task1_ins-ji-0shot-CoT_cri-basic,2026/10/21 21:12,ji-0shot-CoT,basic,827950,1400,44.21,329,91.19,508,27.36,563,31.97,0.00,19.97,65.49,44.44,87.93,38.16,90.48
57,Task1_ins-ji-0shot-CoT_cri-basic,2026/10/21 21:12,ji-0shot-CoT,basic,827950,1400,44.93,319,91.54,516,27.13,565,34.87,0.00,20.95,68.14,20.00,86.76,38.46,90.62
20,Task1_ins-ji-0shot-CoT_cri-basic,2026/10/21 21:10,ji-0shot-CoT,basic,827950,1400,44.36,320,91.25,521,26.68,559,33.99,0.00,20.27,66.67,14.29,87.04,38.03,88.89
15,Task1_ins-ji-0shot-CoT_cri-basic,2026/10/21 21:11,ji-0shot-CoT,basic,827950,1400,44.29,317,92.11,520,27.31,563,33.04,0.00,19.97,65.18,20.00,86.91,38.16,90.62
5,Task1_ins-ji-0shot-CoT_cri-basic,2026/10/21 21:08,ji-0shot-CoT,basic,827950,1400,44.86,329,90.58,520,27.12,551,34.30,0.00,20.73,66.67,50.00,88.57,36.84,89.06
40,Task1_ins-ji-0shot-CoT_cri-basic,2026/10/21 21:13,ji-0shot-CoT,basic,827950,1400,44.57,317,92.11,523,27.72,560,33.39,0.00,20.27,67.83,42.86,86.97,36.84,89.39
37,Task1_ins-ji-0shot-CoT_cri-basic,2026/10/21 21:11,ji-0shot-CoT,basic,827950,1400,44.43,324,90.43,527,27.32,549,33.70,0.00,20.16,66.67,36.36,88.54,37.33,90.48
41,Task1_ins-ji-0shot-CoT_cri-basic,2026/10/21 21:09,ji-0shot-CoT,basic,827950,1400,44.21,326,91.10,514,25.29,560,34.29,0.00,20.19,65.18,25.00,88.25,36.84,89.23
9,Task1_ins-ji-0shot-CoT_cri-basic,2026/10/21 21:09,ji-0shot-CoT,basic,827950,1400,44.71,319,92.16,525,27.05,556,34.17,0.00,20.62,68.18,22.22,88.60,34.62,89.39
30,Task1_ins-ji-0shot-CoT_cri-basic,2026/10/21 21:08,ji-0shot-CoT,basic,827950,1400,44.57,315,91.43,528,26.70,557,35.01,0.00,20.35,65.81,36.36,88.51,37.33,88.89
16,Task1_ins-ji-0shot-dim_cri-basic,2026/10/21 21:08,ji-0shot-dim,basic,860150,1400,44.00,361,72.30,530,29.43,509,39.10,0.00,20.95,71.13,60.00,86.21,34.67,88.71
7,Task1_ins-ji-0shot-dim_cri-basic,2026/10/21 21:07,ji-0shot-dim,basic,860150,1400,43.79,361,73.41,516,29.84,523,37.09,0.00,20.72,71.28,33.33,86.71,35.62,88.89
45,Task1_ins-ji-0shot-dim_cri-basic,2026/10/21 21:12,ji-0shot-dim,basic,860150,1400,43.79,365,73.15,513,29.43,522,37.36,0.00,21.04,71.74,42.86,86.30,36.76,89.06
53,Task1_ins-ji-0shot-dim_cri-basic,2026/10/21 21:09,ji-0shot-dim,basic,860150,1400,44.14,358,73.18,507,29.59,535,38.50,0.00,20.97,70.00,50.00,87.39,34.33,87.88
8,Task1_ins-ji-0shot-dim_cri-basic,2026/10/21 21:10,ji-0shot-dim,basic,860150,1400,43.79,354,74.29,520,27.50,526,39.35,0.00,20.84,71.00,40.00,87.54,35.21,90.48
36,Task1_ins-ji-0shot-dim_cri-basic,2026/10/21 21:10,ji-0shot-dim,basic,860150,1400,44.00,364,71.70,513,29.82,523,38.62,0.00,21.25,71.72,25.00,87.06,32.88,89.06
0,Task1_ins-ji-0shot-dim_cri-basic,2026/10/21 21:09,ji-0shot-dim,basic,860150,1400,43.57,362,72.65,512,29.88,526,36.88,0.00,20.66,70.10,50.00,86.26,34.72,89.06
10,Task1_ins-ji-0shot-dim_cri-basic,2026/10/21 21:12,ji-0shot-dim,basic,860150,1400,43.43,366,71.86,521,30.33,513,36.45,0.00,20.66,73.68,42.86,86.14,35.14,88.71
32,Task1_ins-ji-0shot-dim_cri-basic,2026/10/21 21:11,ji-0shot-dim,basic,860150,1400,43.79,354,73.16,517,28.63,529,38.94,0.00,21.08,70.10,0.00,87.35,34.21,87.88
11,Task1_ins-ji-0shot-dim_cri-basic,2026/10/21 21:13,ji-0shot-dim,basic,860150,1400,43.21,360,72.78,524,29.96,516,36.05,0.00,20.51,71.28,28.57,86.94,34.33,89.23
25,Task1_ins-ji-fewshot_cri-basic,2026/10/21 21:08,ji-fewshot,basic,2254288,1400,37.29,41,80.49,379,49.08,980,30.92,30.00,31.86,38.50,27.36,55.08,17.65,50.00
56,Task1_ins-ji-fewshot_cri-basic,2026/10/21 21:08,ji-fewshot,basic,2255247,1400,38.21,57,84.21,394,50.51,949,30.35,29.59,32.95,45.51,23.53,54.86,21.24,54.95
14,Task1_ins-ji-fewshot_cri-basic,2026/10/21 21:09,ji-fewshot,basic,2257950,1400,37.71,52,84.62,386,48.96,962,30.67,29.25,31.93,36.67,28.70,53.95,21.05,59.81
35,Task1_ins-ji-fewshot_cri-basic,2026/10/21 21:13,ji-fewshot,basic,2251649,1400,36.29,44,70.45,409,48.41,947,29.46,24.56,30.52,41.10,24.55,51.04,22.14,56.60
6,Task1_ins-ji-fewshot_cri-basic,2026/10/21 21:09,ji-fewshot,basic,2240107,1400,35.86,49,69.39,393,46.31,958,29.85,27.07,31.78,40.24,26.85,48.29,18.60,53.77
46,Task1_ins-ji-fewshot_cri-basic,2026/10/21 21:12,ji-fewshot,basic,2244289,1400,37.00,40,85.00,394,50.00,966,29.71,25.86,30.56,40.77,28.57,54.52,21.23,55.66
23,Task1_ins-ji-fewshot_cri-basic,2026/10/21 21:11,ji-fewshot,basic,2250378,1400,35.21,47,78.72,411,44.77,942,28.87,28.38,30.65,34.68,25.22,53.33,14.60,50.91
26,Task1_ins-ji-fewshot_cri-basic,2026/10/21 21:12,ji-fewshot,basic,2268966,1400,37.86,51,80.39,390,49.49,959,30.87,33.67,31.70,41.51,25.00,51.06,21.01,54.46
28,Task1_ins-ji-fewshot_cri-basic,2026/10/21 21:10,ji-fewshot,basic,2241646,1400,37.50,43,76.74,360,53.89,997,29.89,30.00,29.60,40.76,28.21,56.47,19.05,50.48
12,Task1_ins-ji-fewshot_cri-basic,2026/10/21 21:10,ji-fewshot,basic,2255377,1400,35.36,47,91.49,404,47.03,949,27.61,26.94,31.40,36.63,21.95,53.38,20.00,52.22
19,Task1_ins-ji-fewshot-CoT_cri-basic,2026/10/21 21:11,ji-fewshot-CoT,basic,2931489,1400,31.64,44,79.55,415,38.55,941,26.35,28.49,61.76,36.70,21.09,41.32,13.27,23.38
1,Task1_ins-ji-fewshot-CoT_cri-basic,2026/10/21 21:13,ji-fewshot-CoT,basic,2911152,1400,32.43,44,72.73,431,39.91,925,27.03,28.99,54.84,42.51,19.33,42.53,13.00,25.51
21,Task1_ins-ji-fewshot-CoT_cri-basic,2026/10/21 21:10,ji-fewshot-CoT,basic,2916548,1400,31.64,46,71.74,403,41.44,951,25.55,27.44,67.50,38.12,15.32,41.54,11.43,24.77
34,Task1_ins-ji-fewshot-CoT_cri-basic,2026/10/21 21:09,ji-fewshot-CoT,basic,2899329,1400,30.93,39,61.54,408,37.99,953,26.65,26.67,56.76,36.57,23.36,39.33,15.00,23.68
48,Task1_ins-ji-fewshot-CoT_cri-basic,2026/10/21 21:08,ji-fewshot-CoT,basic,2932887,1400,32.86,49,69.39,398,39.45,953,28.23,28.09,45.45,42.29,23.36,41.06,19.05,26.02
51,Task1_ins-ji-fewshot-CoT_cri-basic,2026/10/21 21:11,ji-fewshot-CoT,basic,2919353,1400,31.36,40,65.00,399,40.10,961,26.33,25.70,54.55,35.20,21.43,42.09,17.65,23.49
4,Task1_ins-ji-fewshot-CoT_cri-basic,2026/10/21 21:10,ji-fewshot-CoT,basic,2912441,1400,30.43,41,51.22,408,36.76,951,26.81,25.51,62.07,36.96,26.12,39.54,15.45,21.15
39,Task1_ins-ji-fewshot-CoT_cri-basic,2026/10/21 21:08,ji-fewshot-CoT,basic,2914548,1400,33.50,33,63.64,424,43.16,943,28.10,25.79,67.74,42.13,24.83,44.22,12.37,25.47
52,Task1_ins-ji-fewshot-CoT_cri-basic,2026/10/21 21:12,ji-fewshot-CoT,basic,2929911,1400,32.43,37,72.97,405,41.48,958,27.04,25.70,66.67,42.44,22.48,40.05,17.14,25.08
18,Task1_ins-ji-fewshot-CoT_cri-basic,2026/10/21 21:12,ji-fewshot-CoT,basic,2925780,1400,30.57,34,61.76,413,41.16,953,24.87,22.70,63.64,33.33,19.01,42.28,13.83,24.00

In [49]:
# Average results for runs with the same conditions

mean_list = []
result_fields = ['Total %', 'High Conf %', 'Mid Conf %', 'Low Conf %', 'contains%', 'within%', 'touches%', 'crosses%', 'disjoint%', 'overlaps%', 'equals%']

for title in all_results_df['Title'].unique():
    df = all_results_df[all_results_df['Title'] == title]
    mean_df = df.drop(columns=all_results_df.keys()[6:]).head(1)
    mean_df['Runs'] = df.shape[0]
    
    for field in result_fields:
        mean = df[field].mean()
        mean_df[field] = round(mean, 2)
    mean_list.append(mean_df)

all_mean = pd.concat(mean_list)
all_mean.sort_values('Total %', ascending=False)

,Title,Date,Instructions,Criteria,Input tokens,Results,Runs,Total %,High Conf %,Mid Conf %,Low Conf %,contains%,within%,touches%,crosses%,disjoint%,overlaps%,equals%
5,Task1_ins-ji-0shot-CoT_cri-basic,2026/10/21 21:08,ji-0shot-CoT,basic,827950,1400,10,44.51,91.39,26.97,33.87,0.00,20.35,66.58,31.15,87.81,37.26,89.71
0,Task1_ins-ji-0shot-dim_cri-basic,2026/10/21 21:09,ji-0shot-dim,basic,860150,1400,10,43.75,72.85,29.44,37.83,0.00,20.87,71.20,37.26,86.79,34.79,88.90
3,Task1_ins-ji-0shot_cri-basic,2026/10/21 21:10,ji-0shot,basic,818150,1400,10,43.70,88.05,27.08,33.84,0.00,19.89,68.19,34.79,85.87,34.62,89.77
6,Task1_ins-ji-fewshot_cri-basic,2026/10/21 21:09,ji-fewshot,basic,2240107,1400,10,36.83,80.15,48.84,29.82,28.53,31.30,39.64,25.99,53.20,19.66,53.89
2,Task1_ins-basic_cri-basic,2026/10/21 21:09,basic,basic,764950,1400,10,35.76,91.24,20.75,14.96,1.48,0.35,47.98,38.02,83.26,45.58,91.22
1,Task1_ins-ji-fewshot-CoT_cri-basic,2026/10/21 21:13,ji-fewshot-CoT,basic,2911152,1400,10,31.78,66.95,40.00,26.70,26.51,60.10,38.62,21.63,41.40,14.82,24.26

In [ ]:
# Evaluation of individual predicate accuracy

results_df = pd.read_csv(f'results/Task1_ins-ji_cri-basic.csv')


pred_results = {}
predicates = ["contains","within","touches","crosses","disjoint","overlaps","equals"]
for pred in predicates:
    df = results_df[results_df['choice'] == pred]
    correct = round(df['correct'].mean()*100, 2)
    pred_results[pred] = float(correct)

pred_results

{'contains': 0.0,
 'within': 19.67,
 'touches': 66.67,
 'crosses': 0.0,
 'disjoint': 84.62,
 'overlaps': 32.89,
 'equals': 89.06}

## Archive

In [ ]:
# Retired Instructions and Criteria

instructions_dict = {
    'think': "What topological predicate best describes the relationship between Place A and Place B? The predicates follow the definition of DE-9IM. Think step by step.", # Thinking step by step is contradictory to system one intelligence. It also did not influence results.
}

criteria_dict = {

}

In [ ]:
# SYNCHRONOUS EXECUTION (waaay slower; use asynchronous)
def ask_jev(instructions, criteria, state):
    starttime = datetime.now()
    response = client.system_one(
        state=state,
        questions={
            "Task": Choice(
                instructions=instructions,
                criteria=criteria,
            )
        },
    )
    endtime = datetime.now()
    time = str(endtime - starttime)

    return response, time

client = TypeSafeClient()

instructions = 'think'
criteria = 'basic'
path = create_metadata(instructions, criteria, '1', criteria_dict, instructions_dict)
results = []

df = pd.read_csv('relations.csv')
df = df[:1]

for row in tqdm(df.itertuples(), total=len(df), desc="Prompting"):
    result = {}
    state = f"Geometry A: {row.geometry}, Geometry B: {row.geometry_subject}"
    response, time = ask_jev(instructions_dict[instructions], criteria_dict[criteria], state)

    result['GeomA'] = row.geometry
    result['GeomB'] = row.geometry_subject 
    result['predicate'] = row.predicate
    result['choice'] = response.answers['Task'].choice
    result['probabilities'] = str(response.answers['Task'].probabilities)
    result['confidence'] = response.answers['Task'].confidence
    result['correct'] = int(result['choice'] == result['predicate'])
    result['input_tokens'] = response.usage.input_tokens
    result['output_tokens'] = response.usage.output_tokens
    result['time'] = time
    
    results.append(result)

results_df = pd.DataFrame(results)
save_data(path, results_df)

Saved results/Task1_ins-think_cri-basic_3.json

Processing geometries: 100%|██████████| 1/1 [00:20<00:00, 20.61s/it]

Saved results/Task1_ins-think_cri-basic_3.json

        Summary of results for Task1_ins-think_cri-basic:
        Date: 2026/10/19 17:34
        Tokens used: 506
        Time taken: 00:00:20 (h:m:s)

        Total: 1 results, 0.0% correct.
        Confidence above 80%: 1 results, 0.0% correct.
        Confidence between 50 and 80%: 0 results, nan% correct.
        Confidence below 50%: 0 results, nan% correct.

'results/Task1_ins-think_cri-basic_3.json'

In [ ]:
# Model dump for function create_metadata
async def model_list() -> None:
    async with AsyncTypeSafeClient() as client:
        return await client.models.list()

models = await model_list()
model_dump = models.model_dump()